name: Build All Languages

on:
  workflow_call: 
    inputs:
      include_iframe:
        description: 'Include iFrame'
        type: string
        default: "false"
      deployment_directory:
        description: 'Deployment Directory'
        type: string
        default: ""
      folder_to_deploy_from:
        description: 'Folder To Deploy From'
        type: string
        default: "dist-"

jobs:
  processLanguages:
    name: Process Languages
    runs-on: ubuntu-latest
    outputs:
        langs: ${{ steps.language.outputs.prop }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Language
        id: language
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'build.config.json'
          prop_path: 'buildLanguages'

      - run: echo ${{steps.language.outputs.prop}} 

  build:
    name: Build Multi Language
    runs-on: ubuntu-latest
    needs: processLanguages
    strategy:
      matrix:
        language: ${{ fromJson(needs.processLanguages.outputs.langs) }}

    steps:
      - name: Add SSH key to chekout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.NODE_AUDIO_SSH_KEY }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Update Deployment Directory
        run: deployment_directory=${deployment_directory/${branch}/${{ steps.branch-name.outputs.current_branch }}}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 

      - name: Update build.config.json
        run: echo "`jq '.includeIFrame=${{ inputs.include_iframe }}' build.config.json`" > build.config.json

      - name: Force lang
        run: echo "`jq '.buildSingleLanguage="${{ matrix.language }}"' build.config.json`" > build.config.json

      - name: Get version code
        id: version_code
        uses: lucasfe/version_code_generator@v1.0.0

      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" > ~/.npmrc

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Setup NPM
        run: npm ci --ignore-scripts
      - name: NPM Rebuild
        run: npm rebuild && npm run prepare --if-present

      - name: NPM run build:prod
        run: npm run build:prod

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.scarybserver.com
          username: github@scarybserver.com
          password: ${{ secrets.ftp_password }}
          local-dir: ${{ inputs.folder_to_deploy_from }}${{ matrix.language }}/
          server-dir: ${{ inputs.deployment_directory }}/${{ env.NOW }}/${{ matrix.language }}/

      - name: Zip Artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist-${{ matrix.language }}-${{ env.NOW }}.zip dist-${{ matrix.language }}

      - name: Get dropbox token
        run: echo "DB_ACCES_TOKEN=$(curl https://api.dropbox.com/oauth2/token -d refresh_token=${{secrets.DROPBOX_REFRESH_TOKEN}} -d grant_type=refresh_token -d client_id=${{secrets.DROPBOX_CLIENT_ID}} -d client_secret=${{secrets.DROPBOX_CLIENT_SECRET}} | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")" >> $GITHUB_ENV

      - name: Archive to Dropbox
        run: |
            curl -X POST https://content.dropboxapi.com/2/files/upload \
              --header "Authorization: Bearer ${{ env.DB_ACCES_TOKEN }}" \
              --header "Dropbox-API-Arg: {\"autorename\":false,\"mode\":\"add\",\"mute\":false,\"path\":\"${{ format('/Clients/AppBuilds/{0}/{1}/{0}_{2}_{1}.zip', github.event.repository.name, env.NOW, matrix.language) }}\",\"strict_conflict\":false}" \
              --header "Content-Type: application/octet-stream" \
              --header 'Dropbox-API-Path-Root: {".tag": "root", "root": "10680416816"}' \
              --header "Dropbox-API-Select-Admin: ${{ secrets.DB_ADMIN_ID }}" \
              --data-binary @"dist-${{ matrix.language }}-${{ env.NOW }}.zip"

  post-build:
    name: Post Build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get version code
        id: version_code
        uses: lucasfe/version_code_generator@v1.0.0

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 

      - name: Get Language
        id: language
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'build.config.json'
          prop_path: 'buildLanguages'

      - run: |
          attachments='{"text": "",
              "attachments": [
                {
                  "title": "Multi Language Deployment Finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Project",
                      "short": true,
                      "value": "${{ github.event.repository.name }} Build ${{ steps.version_code.outputs.code }}"
                    },'

          buildLanguages=$(echo ${{steps.language.outputs.prop}} | sed -e 's/\[//g' -e 's/\]//g' -e 's/\"//g'  -e 's/,/ /g; q')

          arr=( $buildLanguages )
          echo $arr

          for i in "${arr[@]}"
          do
              # do stuff with $i
              attachments+='{
              "title": "Link to '"$i"' build",
              "short": false,
              "value": "http://www.scarybserver.com/clients/${{ inputs.deployment_directory }}/${{ env.NOW }}/'"$i"'"
            },'
          done

          attachments+=']
                }
              ]}'

          curl -X POST -H 'Content-type: application/json' --data  "$attachments" ${{ secrets.SLACK_WEBHOOK_URL }}


