name: Node - Build Development

on:
  workflow_call: 
    inputs:
      include_iframe:
        description: 'Include iFrame'
        type: string
        default: "false"
      deployment_directory:
        description: 'Deployment Directory'
        type: string
        default: ""

jobs:
  build:
    name: Build Development
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key to chekout a private repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.NODE_AUDIO_SSH_KEY }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Update build.config.json
        run: echo "`jq '.includeIFrame=${{ inputs.include_iframe }}' build.config.json`" > build.config.json
        
      - name: Force just EN build
        run: echo "`jq '.buildSingleLanguage="en"' build.config.json`" > build.config.json

      - name: Get version code
        id: version_code
        uses: lucasfe/version_code_generator@v1.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          token: ${{ secrets.GH_PAT }}
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Setup NPM
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
      - run: npm rebuild && npm run prepare --if-present
      - run: npm run build:dev

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.scarybserver.com
          username: github@scarybserver.com
          password: ${{ secrets.ftp_password }}
          local-dir: dist-en/
          server-dir: ${{ inputs.deployment_directory }}/${{ steps.version_code.outputs.code }}/

      - name: Notify slack
        run: |
            curl -X POST -H 'Content-type: application/json' --data '{"text": "",
              "attachments": [
                {
                  "title": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Project",
                      "short": true,
                      "value": "${{ github.event.repository.name }} Build ${{ steps.version_code.outputs.code }}"
                    },
                    {
                      "title": "Link to build",
                      "short": false,
                      "value": "http://www.scarybserver.com/clients/${{ github.event.inputs.deployment_directory }}/${{ steps.version_code.outputs.code }}"
                    }
                  ]
                }
              ]}' ${{ secrets.SLACK_WEBHOOK_URL }}
