name: NPM Github Package Public

on: workflow_call

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 16
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         cache: 'npm'
  #         cache-dependency-path: 'package-lock.json'
  #     - run: npm ci
  #     - run: npm test

  publish-gpr:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
