name: SB - Google

on:
  workflow_call: 
    inputs:
      development_build:
        description: 'Development Build'
        type: string
        default: "false"
      bundle_id:
        type: string
        description: 'Bundle ID to use'
        default: ""
      build_aab_bundle:
        description: 'Build AAB Bundle'
        type: string
        default: "false"
      build_obb_bundle:
        description: 'Build OOB'
        type: string
        default: "false"
      destination:
        description: 'Destination of build'
        type: string
        default: "AppCenter"
      android_ndk_version: 
        description: 'optional NDK version'
        type: string
        default: ""
      offset_version_number:
        description: 'Offset Version Number Amount'
        type: string
        default: "0"

jobs:
  buildAllPlatforms:
    name: Build ${{ matrix.platform }} Project
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        platform:
          - Google
    steps:

      - name: Checkout Git repo for project
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          path: ${{ matrix.platform }}
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          clean: false

      - name: Delete XCode Derrived Data
        run : |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Delete XCode Archives
        run : |
          rm -rf ~/Library/Developer/Xcode/Archives

      - name: Delete prior test results
        run : |
          rm -rf ./${{ matrix.platform }}/Tests

      - name: Delete xcode project
        run : |
          rm -rf ./${{ matrix.platform }}/Build

      - name: Kill Unity
        continue-on-error: true
        if: always()
        run: |
           pkill -9 "Unity"

      - uses: akiojin/unity-get-version-github-action@v1.1.13
        id: unity-get-version
        with:
          project-directory: ./${{ matrix.platform }}

      - name: Get Unity Path
        id: unity-path
        timeout-minutes: 5
        run: |
          HUB_PATH="/Applications/Unity Hub.app/Contents/MacOS/Unity Hub"
          PROJECT_VERSIONS=$("$HUB_PATH" -- --headless editors -i)
          PROJECT_PATH="$(echo "$PROJECT_VERSIONS" | grep "${{ steps.unity-get-version.outputs.version }}" | rev | cut -d\  -f1 | rev)/Contents/MacOS/Unity"
          echo $PROJECT_PATH
          echo "::set-output name=unity_path::$PROJECT_PATH"

      - shell: bash
        id: version_code
        run: |
          cd ${GITHUB_WORKSPACE}/${{ matrix.platform }}
          count=$(git rev-list --count HEAD)
          echo "Current count is ${count}"

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is ${current_branch}"
          echo "::set-output name=code::$count"

      - shell: bash
        run: |
          echo ${{ steps.version_code.outputs.code }}
          echo ${{ steps.version_code.outputs.code }} > buildNumber.txt

      - name: Build ${{ matrix.platform }} project
        continue-on-error: true
        timeout-minutes: 15
        run: |
           ${{ steps.unity-path.outputs.unity_path }} -batchmode -nographics -projectPath ./${{ matrix.platform }} -buildTarget Android -executeMethod ScaryBeasties.BuildSettings.Builder.BuildSettings.CommandLineBuild -platform ${{ matrix.platform }} -development ${{ inputs.development_build }} -bundle_id ${{ inputs.bundle_id }} -project_name ${{ github.event.repository.name }} -addressables_profile 'Default' -build_number ${{ steps.version_code.outputs.code }} -build_number_offset '0' -customBuildPath ${{ inputs.build_aab_bundle == 'true' && 'Build/Android/Android.aab' || 'Build/Android/Android.apk' }} -app_bundles ${{ inputs.build_aab_bundle }} -SPLIT_APK ${{ inputs.build_obb_bundle}}

      - name: LowerCase Matrix Name
        id: toLowerCase
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ matrix.platform }}

      - name: Rename apk binary file 
        if: ${{ inputs.build_obb_bundle == 'false' }}
        run: cp ./${{ matrix.platform }}/build/Android/*.apk ./${{ matrix.platform }}/build/Android/Android.apk || true
      - name: Rename aab binary file 
        if: ${{ inputs.build_aab_bundle == 'true' }}
        run: cp ./${{ matrix.platform }}/build/Android/*.aab ./${{ matrix.platform }}/build/Android/Android.aab || true

      - name: Archive to Github
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ steps.version_code.outputs.code }}
          path: ${{ inputs.build_aab_bundle == 'true' && './${{ matrix.platform }}/build/Android/Android.aab' || inputs.build_obb_bundle == 'false' && './${{ matrix.platform }}/build/Android/Android.apk' || '${{ matrix.platform }}' }}

      - name: Notify Teams
        if: success()
        run: |
          cat << EOF > message.json
          {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Google Play Build Uploaded as Github Artifact!","themeColor":"00ff00","title":"$GITHUB_REPOSITORY Google Play Build Uploaded as Github Artifact!","sections":[{"facts":[{"name":"Build Number", "value":"${{ steps.version_code.outputs.code }}"},{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
          EOF

          curl -X POST ${{ secrets.MSTEAMS_WEBHOOK }} --header 'Content-Type: application/json' -d @message.json
     

