name: SB - Google

on:
  workflow_call: 
    inputs:
      development_build:
        description: 'Development Build'
        type: string
        default: "false"
      bundle_id:
        type: string
        description: 'Bundle ID to use'
        default: ""
      build_aab_bundle:
        description: 'Build AAB Bundle'
        type: string
        default: "false"
      build_obb_bundle:
        description: 'Build OOB'
        type: string
        default: "false"
      destination:
        description: 'Destination of build'
        type: string
        default: "AppCenter"
      android_ndk_version: 
        description: 'optional NDK version'
        type: string
        default: ""
      offset_version_number:
        description: 'Offset Version Number Amount'
        type: string
        default: "0"

jobs:
  buildAllPlatforms:
    name: Build ${{ matrix.platform }} Project
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        platform:
          - Google
    steps:

      - name: Checkout Git repo for project
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          path: ${{ matrix.platform }}
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          clean: false

      - name: Delete XCode Derrived Data
        run : |
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Delete XCode Archives
        run : |
          rm -rf ~/Library/Developer/Xcode/Archives

      - name: Delete prior test results
        run : |
          rm -rf ./${{ matrix.platform }}/Tests

      - name: Delete xcode project
        run : |
          rm -rf ./${{ matrix.platform }}/Build

      - name: Kill Unity
        continue-on-error: true
        if: always()
        run: |
           pkill -9 "Unity"

      - uses: akiojin/unity-get-version-github-action@v1.1.13
        id: unity-get-version
        with:
          project-directory: ./${{ matrix.platform }}

      - name: Get Unity Path
        id: unity-path
        timeout-minutes: 5
        run: |
          HUB_PATH="/Applications/Unity Hub.app/Contents/MacOS/Unity Hub"
          PROJECT_VERSIONS=$("$HUB_PATH" -- --headless editors -i)
          PROJECT_PATH="$(echo "$PROJECT_VERSIONS" | grep "${{ steps.unity-get-version.outputs.version }}" | rev | cut -d\  -f1 | rev)/Contents/MacOS/Unity"
          echo $PROJECT_PATH
          echo "::set-output name=unity_path::$PROJECT_PATH"

      - shell: bash
        id: version_code
        run: |
          cd ${GITHUB_WORKSPACE}/${{ matrix.platform }}
          count=$(git rev-list --count HEAD)
          echo "Current count is ${count}"

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is ${current_branch}"
          echo "::set-output name=code::$count"

      - shell: bash
        run: |
          echo ${{ steps.version_code.outputs.code }}
          echo ${{ steps.version_code.outputs.code }} > buildNumber.txt

      - name: Build ${{ matrix.platform }} project
        continue-on-error: true
        timeout-minutes: 15
        run: |
           ${{ steps.unity-path.outputs.unity_path }} -batchmode -nographics -projectPath ./${{ matrix.platform }} -buildTarget ${{ matrix.platform }} -executeMethod ScaryBeasties.BuildSettings.Builder.BuildSettings.CommandLineBuild -platform ${{ matrix.platform }} -development ${{ inputs.development_build }} -bundle_id ${{ inputs.bundle_id }} -project_name ${{ github.event.repository.name }} -addressables_profile 'Default' -build_number ${{ steps.version_code.outputs.code }} -build_number_offset '0' -customBuildPath 'Build/${{ matrix.platform }}'

      - name: LowerCase Matrix Name
        id: toLowerCase
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ matrix.platform }}

      - name: Rename apk binary file 
        if: ${{ inputs.build_obb_bundle == 'false' }}
        run: sudo cp ${{ matrix.platform }}/**/*.apk ${{ matrix.platform }}/Android.apk || true
      - name: Rename aab binary file 
        if: ${{ inputs.build_aab_bundle == 'true' }}
        run: sudo cp ${{ matrix.platform }}/**/*.aab ${{ matrix.platform }}/Android.aab || true

      - name: Upload APK to AppCenter
        if: ${{ inputs.destination == 'AppCenter' }}
        run: bash ./workflows/.github/workflows/uploadToAppCenter.sh phil-bn62 ${{ github.event.repository.name }}_Android ${{ inputs.build_aab_bundle == 'true' && './${{ matrix.platform }}/Android.aab' || './${{ matrix.platform }}/Android.apk' }} ${{secrets.APPCENTER_API_TOKEN}}

      - name: Get dropbox token
        if: ${{ inputs.destination == 'Dropbox' }}
        run: echo "DB_ACCES_TOKEN=$(curl https://api.dropbox.com/oauth2/token -d refresh_token=${{secrets.DROPBOX_REFRESH_TOKEN}} -d grant_type=refresh_token -d client_id=${{secrets.DROPBOX_CLIENT_ID}} -d client_secret=${{secrets.DROPBOX_CLIENT_SECRET}} | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")" >> $GITHUB_ENV

      - name: Archive to Dropbox
        if: ${{ inputs.destination == 'Dropbox' }}
        run: |
            FILES_TO_UPLOAD="${{ matrix.platform }}/**/*"
            for f in $FILES_TO_UPLOAD
            do
                if [[ ! -d "$f" ]]; then
                    BASEDIR=$(dirname "$f")
                    SPLIT_FOLDER=$BASEDIR"_split"
                    FILE="$(basename $f)"
                    sudo mkdir $SPLIT_FOLDER 
                    NEWPATH=$(echo $f | sed "s+"$BASEDIR"+"$SPLIT_FOLDER"+")
                    echo "Processing $f file..."
                    sudo split -db 150000000 "$f" "$NEWPATH"
                    FOLDER=$SPLIT_FOLDER"/*"

                    SESSION_ID=$(curl -X POST https://content.dropboxapi.com/2/files/upload_session/start \
                    --header "Authorization: Bearer ${{ env.DB_ACCES_TOKEN }}" \
                    --header 'Dropbox-API-Path-Root: {".tag": "root", "root": "10680416816"}' \
                    --header "Dropbox-API-Arg: {\"close\":false}" \
                    --header "Content-Type: application/octet-stream" \
                    --header "Dropbox-API-Select-Admin: ${{ secrets.DB_ADMIN_ID }}" \
                    | python3 -c "import sys, json; print(json.load(sys.stdin)['session_id'])")

                    OFFSET=0
                    FOLDER=$SPLIT_FOLDER"/*"
                    for nf in $FOLDER
                    do
                        filesize=$(wc -c $nf | awk '{print $1}')
                        curl -X POST https://content.dropboxapi.com/2/files/upload_session/append_v2 \
                        --header "Authorization: Bearer ${{ env.DB_ACCES_TOKEN }}" \
                        --header 'Dropbox-API-Path-Root: {".tag": "root", "root": "10680416816"}' \
                        --header "Dropbox-API-Arg: {\"close\":false,\"cursor\":{\"offset\":"$OFFSET",\"session_id\":\"$SESSION_ID\"}}" \
                        --header "Content-Type: application/octet-stream" \
                        --header "Dropbox-API-Select-Admin: ${{ secrets.DB_ADMIN_ID }}" \
                        --data-binary @"$nf"

                        OFFSET=$(($OFFSET+$filesize))
                        
                    done

                    curl -X POST https://content.dropboxapi.com/2/files/upload_session/finish \
                        --header "Authorization: Bearer ${{ env.DB_ACCES_TOKEN }}" \
                        --header 'Dropbox-API-Path-Root: {".tag": "root", "root": "10680416816"}' \
                        --header "Dropbox-API-Arg: {\"commit\":{\"autorename\":true,\"mode\":\"add\",\"mute\":false,\"path\":\"/Clients/AppBuilds/${{ github.event.repository.name }}/GooglePlay/${{ steps.version_code.outputs.code }}/$FILE\",\"strict_conflict\":false},\"cursor\":{\"offset\":$OFFSET,\"session_id\":\"$SESSION_ID\"}}" \
                        --header "Content-Type: application/octet-stream" \
                        --header "Dropbox-API-Select-Admin: ${{ secrets.DB_ADMIN_ID }}" \

                    sudo rm -rf $SPLIT_FOLDER
                fi
            done


      - name: Archive to Github
        uses: actions/upload-artifact@v7
        if: ${{ inputs.destination == 'Github' }}
        with:
          name: ${{ github.event.repository.name }}-${{ steps.version_code.outputs.code }}
          path: ${{ inputs.build_aab_bundle == 'true' && '${{ matrix.platform }}/Android.aab' || inputs.build_obb_bundle == 'false' && '${{ matrix.platform }}/Android.apk' || '${{ matrix.platform }}' }}

      - name: Notify Teams
        if: success()
        run: |
          elif [[ ${{ inputs.destination }} == 'Dropbox' ]]
          then
          cat << EOF > message.json
          {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Google Play Build Uploaded To Dropbox!","themeColor":"00ff00","title":"$GITHUB_REPOSITORY Google Play Build Uploaded To Dropbox!","sections":[{"facts":[{"name":"Build Number", "value":"${{ steps.version_code.outputs.code }}"},{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
          EOF
          elif [[ ${{ inputs.destination }} == 'Github' ]]
          then
          cat << EOF > message.json
          {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Google Play Build Uploaded as Github Artifact!","themeColor":"00ff00","title":"$GITHUB_REPOSITORY Google Play Build Uploaded as Github Artifact!","sections":[{"facts":[{"name":"Build Number", "value":"${{ steps.version_code.outputs.code }}"},{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
          EOF
          fi

          curl -X POST ${{ secrets.MSTEAMS_WEBHOOK }} --header 'Content-Type: application/json' -d @message.json
     

